name: fatiharge
description: "fatiharge web page"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:

  #package
  animated_text_kit: ^4.2.2
  auto_route: ^9.2.2

  cupertino_icons: ^1.0.6

  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  flutter_easyloading: ^3.0.5

  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  video_player: ^2.9.2
  image_picker: ^1.0.4
  rive: ^0.13.14
  serverpod_flutter: 2.1.1

  async_button: ^2.0.0-beta.1+2
  fatiharge_client:
    path: ../fatiharge_client
  uikit:
    path: ../../uikit
dev_dependencies:
  auto_route_generator: ^9.0.0
  very_good_analysis: ^5.1.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
    - assets/svg/
    - assets/gif/
    - assets/video/
    - assets/rive/